/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_carplate_CarPlateDetection */

#ifndef _Included_com_example_carplate_CarPlateDetection
#define _Included_com_example_carplate_CarPlateDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_carplate_CarPlateDetection
 * Method:    ImageProc
 * Signature: ([III)Ljava/lang/String;
 */JNIEXPORT jbyteArray JNICALL Java_com_example_carplate_CarPlateDetection_ImageProc(
		JNIEnv *, jclass, jstring, jstring, jstring, jstring);
JNIEXPORT jbyteArray JNICALL Java_com_example_carplate_CarPlateDetection_ImageProcEx(
        		JNIEnv *env, jclass , jintArray ,jintArray ,jstring, jstring ,jstring );
JNIEXPORT jint JNICALL Java_com_example_carplate_CarPlateDetection_annProc(
		JNIEnv *, jclass, jstring);
JNIEXPORT jint JNICALL Java_com_example_carplate_CarPlateDetection_annProcEx(
		JNIEnv *, jclass, jstring);
#ifdef __cplusplus
}
#endif
#endif
